export { default as automatizacion } from './automatizacion.png'
export { default as iluminacion } from './iluminacion.png'
export { default as seguridad } from './seguridad.png'
export { default as casa } from './casa.png'
export { default as CasaModerna } from './casa-moderna.png'
export { default as casa2 } from './casa2.png'
